spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: springboot.project.murashkina@gmail.com
    password: mzjlgxrhipamsqwk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      protocol: smtp
      test-connection: false
  test:
    database:
      replace: none
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.xml
    contexts: dev

server:
  port: 8082